# Generated by Django 3.2 on 2021-04-11 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210327_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
