# Generated by Django 3.2 on 2021-04-11 05:25

from django.db import migrations


def set_default_creator(apps, schema_editor):
    UserAccount = apps.get_model('accounts', 'UserAccount')

    default_creator = UserAccount.objects.filter(is_superuser=True).first()

    for user in UserAccount.objects.all():
        user.creator = default_creator
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_creator'),
    ]

    operations = [
        migrations.RunPython(set_default_creator),
    ]
