# Generated by Django 3.1.3 on 2020-11-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201106_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неудачных попыток')),
                ('unblock_time', models.DateTimeField(blank=True, null=True, verbose_name='Время разблокировки')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
        ),
    ]
