# Generated by Django 3.2 on 2021-04-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
