# Generated by Django 3.1.3 on 2020-11-04 12:39

import company.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(default='Комсомольск-на-Амуре', max_length=64, verbose_name='Город')),
                ('address', models.CharField(max_length=264, verbose_name='Адрес, без города')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Филиалы',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Наименование юр. лица')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН\\ОГРНИП')),
                ('city', models.CharField(default='Комсомольск-на-Амуре', max_length=64, verbose_name='Город')),
                ('address', models.CharField(max_length=264, verbose_name='Адрес, без города')),
                ('email', models.EmailField(max_length=254, verbose_name='Имеил')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Информация об организациях',
                'verbose_name_plural': 'Информация о организациях',
                'ordering': ('is_active', 'title', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('pasport', models.CharField(max_length=264, verbose_name='Паспортные данные')),
                ('pasport_scan', models.FileField(upload_to=company.models.get_employee_pasport_scan_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'pdf', 'zip'])], verbose_name='Скан паспорта')),
                ('status', models.CharField(choices=[('1', 'Работает'), ('0', 'В архиве')], default='1', max_length=16, verbose_name='Статус')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.branch')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работники',
                'ordering': ('status', 'branch', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d/', verbose_name='Логотип компании')),
                ('tagline', models.CharField(max_length=264, verbose_name='Слоган компании')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая настройка')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.businessentity')),
            ],
            options={
                'verbose_name': 'Информация о компаниях',
                'verbose_name_plural': 'Информация о компаниях',
            },
        ),
    ]
