# Generated by Django 3.1.3 on 2020-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fio',
            field=models.CharField(default='', max_length=264, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
