# Generated by Django 3.1.3 on 2020-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201111_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Номер телефона'),
        ),
    ]
