# Generated by Django 3.1.4 on 2020-12-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20201220_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('branch',), 'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='employee_position',
        ),
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
    ]
