# Generated by Django 3.1.4 on 2020-12-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20201231_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Работает'), (0, 'В архиве')], default=1, verbose_name='Статус'),
        ),
    ]
