# Generated by Django 3.1.3 on 2020-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201104_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('title', '-created'), 'verbose_name': 'Юридические лица', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('branch', 'position'), 'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_current',
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Работает'), (0, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=264, verbose_name='Адрес, без города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Комсомольск-на-Амуре', max_length=64, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Имеил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='ogrn',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='ОГРН\\ОГРНИП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Работает'), (0, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Работает'), (0, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Работает'), (0, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='BusinessEntity',
        ),
    ]
