# Generated by Django 3.1.3 on 2020-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201105_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('company', 'Юр. лицо'), ('employee', 'Работник')], default='employee', max_length=16, verbose_name='Тип учетки'),
        ),
    ]
