# Generated by Django 3.1.5 on 2021-03-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='employee_position',
            new_name='position',
        ),
    ]
