# Generated by Django 3.1.5 on 2021-02-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='pasport',
            field=models.CharField(max_length=264, unique=True, verbose_name='Паспортные данные'),
        ),
    ]
